# Generated by Django 5.2.1 on 2025-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('golpe_pix', 'Golpe do Pix'), ('phishing', 'Phishing / Falso Link'), ('falso_suporte', 'Falso Suporte Técnico'), ('roubo_conta', 'Roubo de Conta / Clonagem'), ('site_falso', 'Site Falso / Loja Fake'), ('falso_premio', 'Golpe do Prêmio / Sorteio Falso'), ('engenharia_social', 'Engenharia Social'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
    ]
