# Generated by Django 5.2.1 on 2025-11-19 12:56

import app.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mensagem_mensagem_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=app.models.upload_path),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='categoria',
            field=models.CharField(choices=[('abuso', 'Abuso / Assédio'), ('conteudo_ilegal', 'Conteúdo ilegal'), ('spam', 'Spam'), ('fraude', 'Fraude'), ('outro', 'Outro')], default='Outro', max_length=50),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=45),
        ),
    ]
